# Generated by Django 4.2.3 on 2023-10-06 04:04

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_audio_image_niveau_user_essentials_user_last_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('video', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(upload_to='messages/images/')),
                ('details', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='audio',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='old_pk',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='niveau',
            name='help_dets',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taches',
            name='coef',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='message',
            name='video',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message', to='app.video'),
        ),
    ]
