# Generated by Django 4.2.3 on 2023-10-11 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_niveau_help_dets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='niveau',
            name='cur_task',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
