# Generated by Django 4.2.3 on 2023-10-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_abon_status_verif_transaction_abon_verif'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='only_verified',
            field=models.BooleanField(default=True),
        ),
    ]
