# Generated by Django 4.2.3 on 2023-10-18 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_user_cur_abn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='old_pk',
            field=models.BigIntegerField(default=0),
        ),
    ]
