# Generated by Django 4.2.7 on 2024-01-12 11:12

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_emoji_styleword_alter_user_last_reaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='super_likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='super_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='last',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 12, 11, 12, 3, 299718, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
