# Generated by Django 4.2.7 on 2024-01-30 07:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_user_last_alter_usergroup_matches_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='file',
            field=models.ImageField(max_length=500, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 30, 7, 48, 26, 972558, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
