# Generated by Django 4.2.7 on 2024-02-07 15:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_photos_file_alter_user_last'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='functional',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 7, 15, 24, 17, 462854, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.CreateModel(
            name='Prevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('swipes', models.IntegerField(default=14)),
                ('actual_swipe', models.IntegerField(default=0)),
                ('status', models.CharField(default='pending', max_length=150)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_previsions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previsions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
