# Generated by Django 4.2.7 on 2024-02-10 15:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_message_functional_alter_user_last_prevision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 10, 15, 51, 49, 543171, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.CreateModel(
            name='PaymentPortal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=50)),
                ('transref', models.CharField(max_length=50)),
                ('typ', models.CharField(max_length=20)),
                ('code', models.IntegerField(default=1)),
                ('abn', models.CharField(max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
